version: '3.8'

services:
  backend:
    build:
      context: ./release-notes-agent
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ./release-notes-agent/templates:/app/templates
      - ./release-notes-agent/output:/app/output

  frontend:
    build:
      context: ./release-notes-agent-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend 